name: donfra

services:
  donfra-ws:
    build: .
    image: donfra-ws:local
    ports:
      - "6789:6789"
    environment:
      - PORT=6789
    restart: unless-stopped
    networks:
      - donfra

networks:
  donfra:
    name: donfra
    external: true

